#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <old-branch-name> <new-branch-name>"
    exit 1
fi

OLD_BRANCH=$1
NEW_BRANCH=$2

git branch -m "$OLD_BRANCH" "$NEW_BRANCH"
git branch --unset-upstream 2>/dev/null
git fetch origin
git branch --set-upstream-to=origin/$NEW_BRANCH "$NEW_BRANCH" 2>/dev/null
git push origin -u "$NEW_BRANCH"
git push origin --delete "$OLD_BRANCH"

echo "Branch $OLD_BRANCH renamed to $NEW_BRANCH"
